name: default

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
  workflow_dispatch:

env:
  DOTNET_NOLOGO: true
  NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
  PLUGIN_SDK_CACHE: ${{ github.workspace }}/.plugins/cache

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: setup dotnet
        uses: actions/setup-dotnet@v5
        with:
          cache: true
          cache-dependency-path: ./**/packages.lock.json
          global-json-file: global.json

      - name: restore sample
        run: dotnet restore sample/libdave.sample.csproj --locked-mode

      - name: build sample
        run: dotnet build sample/libdave.sample.csproj --no-restore

  pack:
    if: startsWith(github.ref, 'refs/heads/main') || startsWith(github.ref, 'refs/heads/develop')

    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: setup dotnet
        uses: actions/setup-dotnet@v5
        with:
          cache: true
          cache-dependency-path: ./**/packages.lock.json
          global-json-file: global.json

      - name: restore
        run: dotnet restore --locked-mode

      - name: pack
        run: dotnet build src/libdave.csproj -c Release && dotnet pack src/libdave.csproj -c Release -o dist --no-build

      - name: upload artifact
        uses: actions/upload-artifact@v7s
        with:
          name: libdave
          path: dist

  publish:
    needs: [pack]
    runs-on: ubuntu-latest

    permissions:
      id-token: write

    steps:
      - name: checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: setup dotnet
        uses: actions/setup-dotnet@v5
        with:
          global-json-file: global.json

      - name: nuget login
        uses: NuGet/login@v1
        id: login
        with:
          user: ${{ secrets.NUGET_USER }}

      - name: download artifact
        uses: actions/download-artifact@v8
        with:
          name: libdave

      - name: push
        run: dotnet nuget push "*.nupkg" --api-key ${{steps.login.outputs.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json --skip-duplicate
