name: default

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
  workflow_dispatch:

env:
  ARTIFACT_DIR: ${{ github.workspace }}/dist
  CMAKE_TOOLCHAIN_FILE: ${{ github.workspace }}/cpp/vcpkg/scripts/buildsystems/vcpkg.cmake
  DOTNET_NOLOGO: true
  LIBDAVE_VERSION: 1.1.1
  NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
  VCPKG_BINARY_SOURCES: clear;files,${{ github.workspace }}/vcpkg_cache,readwrite
  VCPKG_CACHE_DIR: ${{ github.workspace }}/vcpkg_cache

jobs:
  build:
    name: build (${{ matrix.rid }})
    runs-on: ${{ matrix.runner }}
    defaults:
      run:
        working-directory: ./cpp
        shell: bash

    strategy:
      fail-fast: false
      matrix:
        include:
          - rid: linux-x64
            runner: ubuntu-24.04
            vcpkg_rid: x64-linux

          - rid: linux-arm64
            runner: ubuntu-24.04-arm
            vcpkg_rid: arm64-linux

          - rid: osx-arm64
            runner: macos-26
            vcpkg_rid: arm64-osx

          - rid: osx-x64
            runner: macos-26-intel
            vcpkg_rid: x64-osx

          - rid: win-x64
            runner: windows-2025
            vcpkg_rid: x64-windows-static

    steps:
      - name: checkout
        uses: actions/checkout@v6
        with:
          repository: discord/libdave
          ref: v${{ env.LIBDAVE_VERSION }}/cpp
          submodules: recursive
          fetch-depth: 0

      - name: setup vcpkg
        run: git -C vcpkg rev-parse HEAD > vcpkg_commit.txt

      - name: cache vcpkg
        id: cache-vcpkg-restore
        uses: actions/cache/restore@v5
        with:
          path: ${{ env.VCPKG_CACHE_DIR }}
          key: vcpkg-${{ matrix.runner }}-openssl-${{ hashFiles('cpp/vcpkg_commit.txt', 'cpp/vcpkg-alts/**') }}
          restore-keys: vcpkg-${{ matrix.runner }}-openssl

      - name: setup tools (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get install -y nasm

      - name: setup tools (macOS)
        if: runner.os == 'macOS'
        run: brew install go nasm

      - name: bootstrap vcpkg (linux/macOS)
        if: runner.os != 'Windows'
        run: ./vcpkg/bootstrap-vcpkg.sh -disableMetrics

      - name: bootstrap vcpkg (windows)
        if: runner.os == 'Windows'
        shell: cmd
        run: .\vcpkg\bootstrap-vcpkg.bat -disableMetrics

      - name: setup build
        run: echo "BUILD_DIR=${{ runner.temp }}/build" >> $GITHUB_ENV

      - name: configure (shared)
        run: |
          make "${{ env.BUILD_DIR }}-shared" \
            BUILD_DIR="${{ env.BUILD_DIR }}-shared" \
            BUILD_TYPE=Release \
            BUILD_SHARED_LIBS=ON \
            TESTING=OFF \
            INSTALL_VCPKG_LICENSES=ON \
            MSVC_RUNTIME_LIBRARY=MultiThreaded

      - name: configure (static)
        run: |
          make "${{ env.BUILD_DIR }}-static" \
            BUILD_DIR="${{ env.BUILD_DIR }}-static" \
            BUILD_TYPE=Release \
            BUILD_SHARED_LIBS=OFF \
            TESTING=OFF \
            INSTALL_VCPKG_LICENSES=ON \
            MSVC_RUNTIME_LIBRARY=MultiThreaded

      - name: build (shared)
        run: |
          make all \
            BUILD_DIR="${{ env.BUILD_DIR }}-shared" \
            BUILD_TYPE=Release

      - name: build (static)
        run: |
          make all \
            BUILD_DIR="${{ env.BUILD_DIR }}-static" \
            BUILD_TYPE=Release

      - name: prepare artifact (linux)
        if: runner.os == 'Linux'
        run: |
          mkdir -p "${{ env.ARTIFACT_DIR }}/bin" "${{ env.ARTIFACT_DIR }}/lib"
          ls -la ${{ env.BUILD_DIR }}-shared && ls -la ${{ env.BUILD_DIR }}-static

          cp "${{ env.BUILD_DIR }}-shared/libdave.so" "${{ env.ARTIFACT_DIR }}/bin/libdave.so"
          cp "${{ env.BUILD_DIR }}-static/libdave.a" "${{ env.ARTIFACT_DIR }}/lib/libdave.a"

          VCPKG_INSTALLED="${{ env.BUILD_DIR }}-static/vcpkg_installed/${{ matrix.vcpkg_rid }}"
          ls -lR "${VCPKG_INSTALLED}/lib"

          # cp "${VCPKG_INSTALLED}/lib/libbytes.a" "${{ env.ARTIFACT_DIR }}/lib/libbytes.a"
          # cp "${VCPKG_INSTALLED}/lib/libcrypto.a" "${{ env.ARTIFACT_DIR }}/lib/libcrypto.a"
          # cp "${VCPKG_INSTALLED}/lib/libhpke.a" "${{ env.ARTIFACT_DIR }}/lib/libhpke.a"
          # cp "${VCPKG_INSTALLED}/lib/libmls_ds.a" "${{ env.ARTIFACT_DIR }}/lib/libmls_ds.a"
          # cp "${VCPKG_INSTALLED}/lib/libmls_vectors.a" "${{ env.ARTIFACT_DIR }}/lib/libmls_vectors.a"
          # cp "${VCPKG_INSTALLED}/lib/libmlspp.a" "${{ env.ARTIFACT_DIR }}/lib/libmlspp.a"
          # cp "${VCPKG_INSTALLED}/lib/libssl.a" "${{ env.ARTIFACT_DIR }}/lib/libssl.a"
          # cp "${VCPKG_INSTALLED}/lib/libtls_syntax.a" "${{ env.ARTIFACT_DIR }}/lib/libtls_syntax.a"

      - name: prepare artifact (macOS)
        if: runner.os == 'macOS'
        run: |
          mkdir -p "${{ env.ARTIFACT_DIR }}/bin" "${{ env.ARTIFACT_DIR }}/lib"
          ls -la ${{ env.BUILD_DIR }}-shared && ls -la ${{ env.BUILD_DIR }}-static

          cp "${{ env.BUILD_DIR }}-shared/libdave.dylib" "${{ env.ARTIFACT_DIR }}/bin/libdave.dylib"
          cp "${{ env.BUILD_DIR }}-static/libdave.a" "${{ env.ARTIFACT_DIR }}/lib/libdave.a"

          VCPKG_INSTALLED="${{ env.BUILD_DIR }}-static/vcpkg_installed/${{ matrix.vcpkg_rid }}"
          ls -lR "${VCPKG_INSTALLED}/lib"

          # cp "${VCPKG_INSTALLED}/lib/libbytes.a" "${{ env.ARTIFACT_DIR }}/lib/libbytes.a"
          # cp "${VCPKG_INSTALLED}/lib/libcrypto.a" "${{ env.ARTIFACT_DIR }}/lib/libcrypto.a"
          # cp "${VCPKG_INSTALLED}/lib/libhpke.a" "${{ env.ARTIFACT_DIR }}/lib/libhpke.a"
          # cp "${VCPKG_INSTALLED}/lib/libmls_ds.a" "${{ env.ARTIFACT_DIR }}/lib/libmls_ds.a"
          # cp "${VCPKG_INSTALLED}/lib/libmls_vectors.a" "${{ env.ARTIFACT_DIR }}/lib/libmls_vectors.a"
          # cp "${VCPKG_INSTALLED}/lib/libmlspp.a" "${{ env.ARTIFACT_DIR }}/lib/libmlspp.a"
          # cp "${VCPKG_INSTALLED}/lib/libssl.a" "${{ env.ARTIFACT_DIR }}/lib/libssl.a"
          # cp "${VCPKG_INSTALLED}/lib/libtls_syntax.a" "${{ env.ARTIFACT_DIR }}/lib/libtls_syntax.a"

      - name: prepare artifact (windows)
        if: runner.os == 'Windows'
        run: |
          mkdir -p "${{ env.ARTIFACT_DIR }}/bin" "${{ env.ARTIFACT_DIR }}/lib"
          ls -la ${{ env.BUILD_DIR }}-shared/Release && ls -la ${{ env.BUILD_DIR }}-static/Release

          cp "${{ env.BUILD_DIR }}-shared/Release/libdave.dll" "${{ env.ARTIFACT_DIR }}/bin/libdave.dll"
          cp "${{ env.BUILD_DIR }}-static/Release/libdave.lib" "${{ env.ARTIFACT_DIR }}/lib/libdave.lib"

          VCPKG_INSTALLED="${{ env.BUILD_DIR }}-static/vcpkg_installed/${{ matrix.vcpkg_rid }}"
          ls -lR "${VCPKG_INSTALLED}/lib"

          # cp "${VCPKG_INSTALLED}/lib/bytes.lib" "${{ env.ARTIFACT_DIR }}/lib/libbytes.lib"
          # cp "${VCPKG_INSTALLED}/lib/crypto.lib" "${{ env.ARTIFACT_DIR }}/lib/libcrypto.lib"
          # cp "${VCPKG_INSTALLED}/lib/hpke.lib" "${{ env.ARTIFACT_DIR }}/lib/libhpke.lib"
          # cp "${VCPKG_INSTALLED}/lib/mls_ds.lib" "${{ env.ARTIFACT_DIR }}/lib/libmls_ds.lib"
          # cp "${VCPKG_INSTALLED}/lib/mls_vectors.lib" "${{ env.ARTIFACT_DIR }}/lib/libmls_vectors.lib"
          # cp "${VCPKG_INSTALLED}/lib/mlspp.lib" "${{ env.ARTIFACT_DIR }}/lib/libmlspp.lib"
          # cp "${VCPKG_INSTALLED}/lib/ssl.lib" "${{ env.ARTIFACT_DIR }}/lib/libssl.lib"
          # cp "${VCPKG_INSTALLED}/lib/tls_syntax.lib" "${{ env.ARTIFACT_DIR }}/lib/libtls_syntax.lib"

      - name: upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: libdave-${{ matrix.rid }}
          path: ${{ env.ARTIFACT_DIR }}

      - name: Post cache vcpkg
        if: steps.cache-vcpkg-restore.outputs.cache-hit != 'true'
        uses: actions/cache/save@v5
        with:
          key: ${{ steps.cache-vcpkg-restore.outputs.cache-primary-key }}
          path: ${{ env.VCPKG_CACHE_DIR }}

  pack:
    needs: [build]
    runs-on: ubuntu-latest

    permissions:
      checks: write
      contents: read

    steps:
      - name: checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: setup dotnet
        uses: actions/setup-dotnet@v5
        with:
          cache: true
          cache-dependency-path: ./**/packages.lock.json
          global-json-file: global.json

      - name: download artifacts
        uses: actions/download-artifact@v8
        with:
          pattern: libdave-*
          merge-multiple: false
          path: artifact

      - name: restore
        shell: pwsh
        run: |
          dotnet restore --locked-mode

          $artifact = Join-Path ${{ github.workspace }} "artifact"
          $output = Join-Path ${{ github.workspace }} "src"

          foreach ($runtime in @("linux-arm64", "linux-x64", "osx-arm64", "osx-x64", "win-x64")) {
            foreach ($file in Get-ChildItem -Path ([System.IO.Path]::Combine($artifact, "libdave-$runtime", "lib")) -Recurse -File) {
              New-Item -ItemType Directory -Path ([System.IO.Path]::Combine($output, "static", $runtime, "native")) -Force | Out-Null

              $destination = [System.IO.Path]::Combine($output, "static", $runtime, "native", $file.Name)
              Move-Item -Path $file.FullName -Destination $destination -Force

              Write-Host "[!] Moved ${file.FullName} to '$destination'"
            }

            foreach ($file in Get-ChildItem -Path ([System.IO.Path]::Combine($artifact, "libdave-$runtime", "bin")) -Recurse -File) {
              New-Item -ItemType Directory -Path ([System.IO.Path]::Combine($output, "shared", $runtime, "native")) -Force | Out-Null

              $destination = [System.IO.Path]::Combine($output, "shared", $runtime, "native", $file.Name)
              Move-Item -Path $file.FullName -Destination $destination -Force

              Write-Host "[!] Moved ${file.FullName} to '$destination'"
            }
          }

      - name: pack
        run: dotnet build src/libdave.csproj -c Release -p:LibDaveVersion="${{ env.LIBDAVE_VERSION }}" && dotnet pack src/libdave.csproj -c Release -o dist --no-build -p:LibDaveVersion="${{ env.LIBDAVE_VERSION }}"

      - name: upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: libdave-nuget
          path: dist

  publish:
    needs: [pack]
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: setup dotnet
        uses: actions/setup-dotnet@v5
        with:
          global-json-file: global.json

      - name: nuget login
        uses: NuGet/login@v1
        id: login
        with:
          user: ${{ secrets.NUGET_USER }}

      - name: download artifact
        uses: actions/download-artifact@v8
        with:
          name: libdave-nuget

      - name: push
        run: dotnet nuget push "*.nupkg" --api-key ${{steps.login.outputs.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json --skip-duplicate
